<?php
/**
 * @file
 * speedysito_deploy_website.features.uuid_bean.inc
 */

/**
 * Implements hook_uuid_features_default_beans().
 */
function speedysito_deploy_website_uuid_features_default_beans() {
  $beans = array();

  $beans[] = array(
    'label' => 'SpeedySito - IES',
    'description' => NULL,
    'title' => 'I.E.S. srl',
    'type' => 'block',
    'data' => array(
      'view_mode' => 'default',
    ),
    'delta' => 'speedysito---ies',
    'view_mode' => 'default',
    'created' => 1401547114,
    'log' => '',
    'uid' => 1,
    'default_revision' => 1,
    'revisions' => array(),
    'vuuid' => '2dc37f5a-5424-41fb-9415-7ae0263ca0b0',
    'uuid' => '257bfb29-3d20-4a43-86fe-2e0177725f01',
    'field_body' => array(
      'und' => array(
        0 => array(
          'value' => '<p><span style="font-size:14px">SpeedySito è un prodotto della I.E.S. srl.</span></p>

<p><span style="font-size:14px">Siamo a vostra disposizione per ogni esigenza informatica.</span></p>

<div style="text-align: right;"><span style="font-size:14px"><a href="/about">Scopri chi siamo</a></span></div>',
          'format' => 'editor',
          'safe_value' => '<p><span style="font-size:14px">SpeedySito è un prodotto della I.E.S. srl.</span></p>

<p><span style="font-size:14px">Siamo a vostra disposizione per ogni esigenza informatica.</span></p>

<div style="text-align: right;"><span style="font-size:14px"><a href="http://devel.speedysito.it/about">Scopri chi siamo</a></span></div>',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $beans[] = array(
    'label' => 'SpeedySito - Services Basic',
    'description' => NULL,
    'title' => 'SpeedySito Basic',
    'type' => 'block',
    'data' => array(
      'view_mode' => 'default',
    ),
    'delta' => 'speedysito---services-basic',
    'view_mode' => 'default',
    'created' => 1401544955,
    'log' => '',
    'uid' => 1,
    'default_revision' => 1,
    'revisions' => array(),
    'vuuid' => '2c52a858-26df-454b-b681-a50b675043b3',
    'uuid' => '2ce1caf6-77c4-4514-a5c1-08294233b73d',
    'field_body' => array(
      'und' => array(
        0 => array(
          'value' => '<div class="speedysito-services-content">
<p class="rtejustify">Per il libero professionista e la piccola impresa che vogliono iniziare a muovere i primi passi nella rete.</p>
</div>

<div class="speedysito-services-moreinfo rtecenter"><a class="testround speedysito-basic-moreinfo" href="/prodotto/speedysito-basic">Ulteriori informazioni</a></div>
',
          'format' => 'editor',
          'safe_value' => '<div class="speedysito-services-content">
<p class="rtejustify">Per il libero professionista e la piccola impresa che vogliono iniziare a muovere i primi passi nella rete.</p>
</div>

<div class="speedysito-services-moreinfo rtecenter"><a class="testround speedysito-basic-moreinfo" href="http://devel.speedysito.it/prodotto/speedysito-basic">Ulteriori informazioni</a></div>
',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $beans[] = array(
    'label' => 'SpeedySito - Footer Message',
    'description' => NULL,
    'title' => '',
    'type' => 'block',
    'data' => array(
      'view_mode' => 'default',
    ),
    'delta' => 'speedysito---footer-message',
    'view_mode' => 'default',
    'created' => 1401548243,
    'log' => '',
    'uid' => 1,
    'default_revision' => 1,
    'revisions' => array(),
    'vuuid' => '47c05cce-4832-486b-a6e9-9ddec9462ada',
    'uuid' => '5236a4aa-3732-4d7f-ba58-92f81251be01',
    'field_body' => array(
      'und' => array(
        0 => array(
          'value' => '<div class="footer-message-text-inner inner clearfix" id="footer-message-text-inner"><span style="font-size:13px">SpeedySito è un prodotto di <a href="http://www.gruppoies.net" target="_blank">I.E.S.</a> SrL<br />
Corso Massimo D\'Azeglio, 38/A<br />
10015 Ivrea (TO)<br />
CF e PI IT05464360014</span></div>',
          'format' => 'editor',
          'safe_value' => '<div class="footer-message-text-inner inner clearfix" id="footer-message-text-inner"><span style="font-size:13px">SpeedySito è un prodotto di <a href="http://www.gruppoies.net" target="_blank">I.E.S.</a> SrL<br />
Corso Massimo D\'Azeglio, 38/A<br />
10015 Ivrea (TO)<br />
CF e PI IT05464360014</span></div>',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $beans[] = array(
    'label' => 'SpeedySito - Intro',
    'description' => NULL,
    'title' => '',
    'type' => 'block',
    'data' => array(
      'view_mode' => 'default',
    ),
    'delta' => 'speedysito---intro',
    'view_mode' => 'default',
    'created' => 1401544282,
    'log' => '',
    'uid' => 1,
    'default_revision' => 1,
    'revisions' => array(),
    'vuuid' => 'afcef176-e1c6-4e3a-b899-d31f1c9d6c4b',
    'uuid' => '5d6e3f43-491e-42c7-946b-efefd5da987c',
    'field_body' => array(
      'und' => array(
        0 => array(
          'value' => '<p><span style="color:#FFFFFF">SpeedySito è un sito internet completo e già pronto per le esigenze più diffuse, basta solo sostituire i testi e le immagini precaricate con le vostre. E se vorrete espanderlo o modificarlo in un secondo momento, potrete farlo ogni volta che vorrete, e senza nessun costo aggiuntivo.</span></p>

<p><span style="color:#FFFFFF"><strong>Inoltre, grazie alla licenza di SpeedySito, il risultato rimarrà di vostra proprietà!</strong></span></p>
',
          'format' => 'editor',
          'safe_value' => '<p><span style="color:#FFFFFF">SpeedySito è un sito internet completo e già pronto per le esigenze più diffuse, basta solo sostituire i testi e le immagini precaricate con le vostre. E se vorrete espanderlo o modificarlo in un secondo momento, potrete farlo ogni volta che vorrete, e senza nessun costo aggiuntivo.</span></p>

<p><span style="color:#FFFFFF"><strong>Inoltre, grazie alla licenza di SpeedySito, il risultato rimarrà di vostra proprietà!</strong></span></p>
',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $beans[] = array(
    'label' => 'SpeedySito - Services Professional',
    'description' => NULL,
    'title' => 'SpeedySito Professional',
    'type' => 'block',
    'data' => array(
      'view_mode' => 'default',
    ),
    'delta' => 'speedysito---services-profession',
    'view_mode' => 'default',
    'created' => 1401545130,
    'log' => '',
    'uid' => 1,
    'default_revision' => 1,
    'revisions' => array(),
    'vuuid' => 'e6717c76-f3c5-4041-b14f-59dfad0c1427',
    'uuid' => '77a57549-835e-4f74-8625-262d18df90d3',
    'field_body' => array(
      'und' => array(
        0 => array(
          'value' => '<div class="speedysito-services-content">
<p class="rtejustify">Il pacchetto PROFESSIONAL è quello che offre il miglio rapporto qualità/prezzo per una presenza web significativa.</p>
</div>

<div class="speedysito-services-moreinfo rtecenter"><a class="testround speedysito-professional-moreinfo" href="/prodotto/speedysito-professional">Ulteriori informazioni</a></div>
',
          'format' => 'editor',
          'safe_value' => '<div class="speedysito-services-content">
<p class="rtejustify">Il pacchetto PROFESSIONAL è quello che offre il miglio rapporto qualità/prezzo per una presenza web significativa.</p>
</div>

<div class="speedysito-services-moreinfo rtecenter"><a class="testround speedysito-professional-moreinfo" href="http://devel.speedysito.it/prodotto/speedysito-professional">Ulteriori informazioni</a></div>
',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $beans[] = array(
    'label' => 'SpeedySito - Vantaggi',
    'description' => NULL,
    'title' => 'Il tuo nuovo sito web',
    'type' => 'block',
    'data' => array(
      'view_mode' => 'default',
    ),
    'delta' => 'speedysito---vantaggi',
    'view_mode' => 'default',
    'created' => 1401544375,
    'log' => '',
    'uid' => 1,
    'default_revision' => 1,
    'revisions' => array(),
    'vuuid' => '664e9de0-33b2-4a64-9740-533bfaa192b0',
    'uuid' => '86da7b2a-e3f9-4b92-b761-b9610e64f1b3',
    'field_body' => array(
      'und' => array(
        0 => array(
          'value' => '<ul>
	<li><span style="color:#FFFFFF">Economico</span></li>
	<li><span style="color:#FFFFFF">Personalizzabile</span></li>
	<li><span style="color:#FFFFFF">Ottimizzato per motori di ricerca</span></li>
</ul>
',
          'format' => 'editor',
          'safe_value' => '<ul>
	<li><span style="color:#FFFFFF">Economico</span></li>
	<li><span style="color:#FFFFFF">Personalizzabile</span></li>
	<li><span style="color:#FFFFFF">Ottimizzato per motori di ricerca</span></li>
</ul>
',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $beans[] = array(
    'label' => 'SpeedySito - Services Enterprise',
    'description' => NULL,
    'title' => 'SpeedySito Enterprise',
    'type' => 'block',
    'data' => array(
      'view_mode' => 'default',
    ),
    'delta' => 'speedysito---services-enterprise',
    'view_mode' => 'default',
    'created' => 1401545228,
    'log' => '',
    'uid' => 1,
    'default_revision' => 1,
    'revisions' => array(),
    'vuuid' => '939bce7e-5d8d-4fc9-9e40-93e14872a2e0',
    'uuid' => 'd75f27d0-e7e8-44ec-bdc1-226c11879818',
    'field_body' => array(
      'und' => array(
        0 => array(
          'value' => '<div class="speedysito-services-content">
<p class="rtejustify">Il pacchetto ENTERPRISE è la soluzione ideale per la media e la grande impresa.</p>
</div>

<div class="speedysito-services-moreinfo rtecenter"><a class="testround speedysito-enterprise-moreinfo" href="/prodotto/speedysito-enterprise">Ulteriori informazioni</a></div>
',
          'format' => 'editor',
          'safe_value' => '<div class="speedysito-services-content">
<p class="rtejustify">Il pacchetto ENTERPRISE è la soluzione ideale per la media e la grande impresa.</p>
</div>

<div class="speedysito-services-moreinfo rtecenter"><a class="testround speedysito-enterprise-moreinfo" href="http://devel.speedysito.it/prodotto/speedysito-enterprise">Ulteriori informazioni</a></div>
',
        ),
      ),
    ),
    'url_alias' => array(),
  );
  return $beans;
}
